ALTER TABLE analysis_group DROP COLUMN deleted;
ALTER TABLE analysis_group_label DROP COLUMN deleted;
ALTER TABLE analysis_group_state DROP COLUMN deleted;
ALTER TABLE analysis_group_value DROP COLUMN deleted;
ALTER TABLE container DROP COLUMN deleted;
ALTER TABLE container_label DROP COLUMN deleted;
ALTER TABLE container_state DROP COLUMN deleted;
ALTER TABLE container_value DROP COLUMN deleted;
ALTER TABLE experiment DROP COLUMN deleted;
ALTER TABLE experiment_label DROP COLUMN deleted;
ALTER TABLE experiment_state DROP COLUMN deleted;
ALTER TABLE experiment_value DROP COLUMN deleted;
ALTER TABLE file_thing DROP COLUMN deleted;
ALTER TABLE itx_container_container DROP COLUMN deleted;
ALTER TABLE itx_container_container_state DROP COLUMN deleted;
ALTER TABLE itx_container_container_value DROP COLUMN deleted;
ALTER TABLE itx_experiment_experiment DROP COLUMN deleted;
ALTER TABLE itx_experiment_experiment_state DROP COLUMN deleted;
ALTER TABLE itx_experiment_experiment_value DROP COLUMN deleted;
ALTER TABLE itx_protocol_protocol DROP COLUMN deleted;
ALTER TABLE itx_protocol_protocol_state DROP COLUMN deleted;
ALTER TABLE itx_protocol_protocol_value DROP COLUMN deleted;
ALTER TABLE itx_subject_container DROP COLUMN deleted;
ALTER TABLE itx_subject_container_state DROP COLUMN deleted;
ALTER TABLE itx_subject_container_value DROP COLUMN deleted;
ALTER TABLE ls_interaction DROP COLUMN deleted;
ALTER TABLE ls_thing DROP COLUMN deleted;
ALTER TABLE ls_thing_label DROP COLUMN deleted;
ALTER TABLE ls_thing_state DROP COLUMN deleted;
ALTER TABLE ls_thing_value DROP COLUMN deleted;
ALTER TABLE protocol DROP COLUMN deleted;
ALTER TABLE protocol_label DROP COLUMN deleted;
ALTER TABLE protocol_state DROP COLUMN deleted;
ALTER TABLE protocol_value DROP COLUMN deleted;
ALTER TABLE subject DROP COLUMN deleted;
ALTER TABLE subject_label DROP COLUMN deleted;
ALTER TABLE subject_state DROP COLUMN deleted;
ALTER TABLE subject_value DROP COLUMN deleted;
ALTER TABLE treatment_group DROP COLUMN deleted;
ALTER TABLE treatment_group_label DROP COLUMN deleted;
ALTER TABLE treatment_group_state DROP COLUMN deleted;
ALTER TABLE treatment_group_value DROP COLUMN deleted;

ALTER TABLE analysis_group ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE analysis_group_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE analysis_group_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE analysis_group_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE container ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE container_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE container_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE container_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE experiment ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE experiment_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE experiment_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE experiment_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE file_thing ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_container_container ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_container_container_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_container_container_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_experiment_experiment ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_experiment_experiment_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_experiment_experiment_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_protocol_protocol ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_protocol_protocol_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_protocol_protocol_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_subject_container ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_subject_container_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE itx_subject_container_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE ls_interaction ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE ls_thing ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE ls_thing_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE ls_thing_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE ls_thing_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE protocol ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE protocol_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE protocol_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE protocol_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE subject ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE subject_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE subject_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE subject_value ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE treatment_group ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE treatment_group_label ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE treatment_group_state ADD COLUMN deleted boolean DEFAULT false;
ALTER TABLE treatment_group_value ADD COLUMN deleted boolean DEFAULT false;

UPDATE experiment SET deleted = true WHERE ignored = true AND deleted = false;
UPDATE protocol SET deleted = true WHERE ignored = true AND deleted = false;

