source("public/src/modules/serverAPI/src/server/labSynch_JSON_library.R")

saveLabelSequence(createLabelSequence(labelPrefix="SITX", thingTypeAndKind="interaction_subjectContainer"))
saveLabelSequence(createLabelSequence(labelPrefix="CITX", thingTypeAndKind="interaction_containerContainer"))
saveLabelSequence(createLabelSequence(labelPrefix="CONT", thingTypeAndKind="material_container"))
saveLabelSequence(createLabelSequence(labelPrefix="AG", thingTypeAndKind="document_analysis group"))
saveLabelSequence(createLabelSequence(labelPrefix="TG", thingTypeAndKind="document_treatment group"))
saveLabelSequence(createLabelSequence(labelPrefix="SUBJ", thingTypeAndKind="document_subject"))
saveLabelSequence(createLabelSequence(labelPrefix="PROT", thingTypeAndKind="document_protocol"))
saveLabelSequence(createLabelSequence(labelPrefix="EXPT", thingTypeAndKind="document_experiment"))