getFormatSettings <- function() {
  formatSettings <- list(
    rawOnly = list(
      "Custom Example" = list(
        annotationType = "",
        hideAllData = FALSE,
        extraHeaders = data.frame(),
        sigFigs = 3,
        stateGroups = list(list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "treatment",
                                valueKinds = c("Dose"),
                                includesOthers = FALSE,
                                includesCorpName = TRUE),
                           list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "raw data",
                                valueKinds = c("Weight", "Force", "Favorite Color", "Mouse Name"),
                                includesOthers = TRUE,
                                includesCorpName = FALSE))
      ),
      "Example2" = list(
        annotationType = "s_general",
        hideAllData = FALSE,
        extraHeaders = data.frame(),
        sigFigs = 3,
        curveNames = c("PO IV pk curve id", "PO pk curve id", "IV pk curve id"),
        stateGroups = list(list(entityKind = "analysis group",
                                stateType = "data",
                                stateKind = "calculated data",
                                valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                               "PO - HL_Lambda_z", "PO - Tmax", 
                                               "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                               "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                               "IV - Vss_obs", "PO - Vss_obs"),
                                includesOthers = FALSE,
                                includesCorpName = TRUE),
                           list(entityKind = "container",
                                stateType = "metadata", 
                                stateKind = "animal information", 
                                valueKinds = c("Gender", "Species"),
                                includesOthers = FALSE,
                                includesCorpName = FALSE),
                           list(entityKind = "container",
                                labelType = "name",
                                labelKind = "container name",
                                labelText = "Animal",
                                valueKinds = c("Animal"),
                                includesOthers = FALSE,
                                includesCorpName = FALSE),
                           list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "treatment",
                                valueKinds = c("Formulation", "IV - Route", "PO - Route", "Dose", "IV - food_effect", "PO - food_effect"),
                                includesOthers = FALSE,
                                includesCorpName = TRUE),
                           list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "raw data",
                                valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                               "PO - HL_Lambda_z", "IV - Tmax", "PO - Tmax", 
                                               "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                               "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                               "IV - Vss_obs", "PO - Vss_obs"),
                                includesOthers = TRUE,
                                includesCorpName = FALSE))
      ), 
      "Custom Example 3" = list(
        hideAllData = FALSE,
        sigFigs = 3,
        extraHeaders = data.frame(),
        stateGroups = list(list(entityKind = "analysis group",
                                stateType = "data",
                                stateKind = "results",
                                valueKinds = c("Weight", "Force", "Favorite Color", "Dose"),
                                includesOthers = FALSE,
                                includesCorpName = TRUE),
                           list(entityKind = "container",
                                stateType = "metadata",
                                stateKind = "animal information",
                                valueKinds = c("Mouse Name"),
                                includesOthers = FALSE,
                                includesCorpName = FALSE),
                           list(entityKind = "container",
                                labelType = "name",
                                labelKind = "container name",
                                labelText = "Animal",
                                valueKinds = c("Mouse Name"),
                                includesOthers = FALSE,
                                includesCorpName = FALSE),
                           list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "treatment",
                                valueKinds = c("Weight", "Dose"),
                                includesOthers = FALSE,
                                includesCorpName = TRUE),
                           list(entityKind = "subject",
                                stateType = "data",
                                stateKind = "raw data",
                                valueKinds = c("Force", "Favorite Color", "Mouse Name"),
                                includesOthers = TRUE,
                                includesCorpName = FALSE))
      )
    ),
    doseResponseRender = list(
      "Ki Fit" = list(
        doseResponseKinds = list(
          "algorithm flag status",
          "batch code",
          "category",
          "curve id",
          "curve name",
          "curveErrorsClob",
          "fitSettings",
          "fitSummaryClob",
          "Kd",
          "Fitted Kd",
          "Fitted Ki",
          "Ligand Conc",
          "Fitted Ligand Conc",
          "Fitted Max",
          "Fitted Min",
          "Ki",
          "Max",
          "Min",
          "parameterStdErrorsClob",
          "Rendering Hint",
          "reportedValuesClob",
          "rSquared",
          "SSE",
          "SST",
          "user flag status"
        )
      ),
      "Michaelis-Menten" = list(
        doseResponseKinds = list(
          "algorithm flag status",
          "batch code",
          "category",
          "curve id",
          "curve name",
          "curveErrorsClob",
          "fitSettings",
          "fitSummaryClob",
          "Et",
          "Fitted Et",
          "Fitted Km",
          "Fitted VMax",
          "kcat",
          "kcat/Km",
          "Km",
          "parameterStdErrorsClob",
          "Rendering Hint",
          "reportedValuesClob",
          "rSquared",
          "SSE",
          "SST",
          "user flag status",
          "VMax"
        )
      ),
      "4 parameter D-R" = list(
        doseResponseKinds = list(
          "algorithm flag status",
          "batch code",
          "category",
          "curve id",
          "curve name",
          "curveErrorsClob",
          "EC50",
          "fitSettings",
          "fitSummaryClob",
          "Fitted EC50",
          "Fitted Max",
          "Fitted Min",
          "Fitted Slope",
          "Max",
          "Min",
          "parameterStdErrorsClob",
          "Rendering Hint",
          "reportedValuesClob",
          "rSquared",
          "Slope",
          "SSE",
          "SST",
          "user flag status"
        )
      ),
      "4 parameter D-R IC50" = list(
        doseResponseKinds = list(
          "algorithm flag status",
          "batch code",
          "category",
          "curve name",
          "curveErrorsClob",
          "fitSettings",
          "fitSummaryClob",
          "Fitted IC50",
          "Fitted Max",
          "Fitted Min",
          "Fitted Slope",
          "IC50",
          "Max",
          "Min",
          "parameterStdErrorsClob",
          "Rendering Hint",
          "reportedValuesClob",
          "rSquared",
          "Slope",
          "SSE",
          "SST",
          "user flag status",
          "curve id"
        )
      ),
      "Substrate Inhibition" = list(
        doseResponseKinds = list(
          "algorithm flag status",
          "category",
          "curve id",
          "curve name",
          "curveErrorsClob",
          "fitSettings",
          "fitSummaryClob",
          "Et",
          "Fitted Et",
          "Fitted Ki",
          "Fitted Km",
          "Fitted VMax",
          "kcat",
          "kcat/Km",
          "Ki",
          "Km",
          "parameterStdErrorsClob",
          "Rendering Hint",
          "reportedValuesClob",
          "rSquared",
          "SSE",
          "SST",
          "user flag status",
          "VMax"
        )
      )
    )
  )
  return(formatSettings)
} 