<script type="text/template" id="MetaLotView_template">
	
	<h1 class="formTitle"></h1>
	<div class="LotForm_ParentView"></div>
	<div class="LotForm_SaltFormView"></div>
	<div class="LotForm_LotView"></div>
	<div class="MetaLotViewButtons buttons">
		<a class="button saveButton" href="#" onclick="this.blur(); return false;"></a>
		<a class="button cancelButton" href="#" onclick="this.blur(); return false;"></a>
		<a class="button backButton" href="#" onclick="this.blur(); return false;"></a>
        <a class="button newLotButton" href="#" onclick="this.blur(); return false;"></a>
	</div>
    <div class="floatingPanel NewLotSuccessView"></div>
	<div class="bv_lotInventory"></div>

</script>
