<script type="text/template" id="NewIsotopeView_template">
	<h2 class="form_title">Register New Isotope:</h2>
	<hr>
	<div>
		<label class="FormLabel">Isotope Name </label>
		<input type=text class="isotope_name" />
	</div>
	<div>
		<label class="FormLabel">Isotope Abbreviation </label>
		<input type=text class="isotope_abbrev" />
	</div>
	<div>
		<label class="FormLabel">Isotope Mass Change </label>
		<input type=text class="isotope_massChange" />
	</div>
	<input type=button class="saveNewIsotopeButton" />
	<input type=button class="cancelNewIsotopeButton" />
</script>