<script type="text/template" id="NewLotSuccessView_template">
	<h2 class="form_title">New <span class="lotOrBatch"></span> Registered Successfully:</h2>
	<hr>
	<div class="labelCorpName">
		<label>Name: </label>
		<span class="corpName" />
        <span class="labelBuid" style="display:none">
            <label>BUID: </label>
            <span class="buid" />
        </span>
	</div>
	<div class="MetaLotViewButtons">
		<a class="editLotButton" href="#" onclick="this.blur(); return false;"></a>
        <a class="newLotButton" href="#" onclick="this.blur(); return false;"></a>
		<a class="closeButton" href="#" onclick="this.blur(); return false;"></a>
	</div>
</script>