// Generated by CoffeeScript 1.9.3
(function() {
  var _, batchIds, databaseName, db, dbConnectionString, findWellsWithBatchCode, generatePlates, generateWells, i, mongoPort, mongojs, plate, results;

  _ = require('lodash');

  mongojs = require('mongojs');

  mongoPort = 27017;

  databaseName = "plateRegistration";

  dbConnectionString = process.env.DOCKER_HOST_IP + ":" + mongoPort + "/" + databaseName;

  console.log("dbConnectionString");

  console.log(dbConnectionString);

  db = mongojs(dbConnectionString, ['plates', 'wells']);

  batchIds = (function() {
    results = [];
    for (i = 1; i <= 100; i++){ results.push(i); }
    return results;
  }).apply(this);

  generatePlates = function(numberOfPlates, plateType) {
    var j, plateIndex, plates, results1;
    plateIndex = 1;
    plates = [];
    _.each((function() {
      results1 = [];
      for (var j = 1; 1 <= numberOfPlates ? j <= numberOfPlates : j >= numberOfPlates; 1 <= numberOfPlates ? j++ : j--){ results1.push(j); }
      return results1;
    }).apply(this), function(plateIdx) {
      var plate;
      plate = {
        objectGraphSchemaVersion: 1,
        codeName: "CONT-" + plateIdx,
        deleted: false,
        id: plateIndex,
        ignored: false,
        lsKind: "plate",
        wells: generateWells(plateType),
        lsLabels: [
          {
            deleted: false,
            id: 144523,
            ignored: false,
            labelText: "C1123312",
            lsKind: "barcode",
            lsTransaction: 1,
            lsType: "barcode",
            lsTypeAndKind: "barcode_barcode",
            physicallyLabled: true,
            preferred: true,
            recordedBy: "acas",
            recordedDate: 1455323304684,
            version: 0
          }
        ],
        lsStates: [
          {
            deleted: false,
            id: 124184,
            ignored: false,
            lsKind: "container",
            lsTransaction: 1,
            lsType: "metadata",
            lsTypeAndKind: "metadata_container",
            lsValues: [
              {
                codeKind: "plate type",
                codeOrigin: "ACAS DDICT",
                codeType: "plate type",
                codeTypeAndKind: "plate type_plate type",
                codeValue: "hitpick master plate",
                deleted: false,
                id: 497530,
                ignored: false,
                lsKind: "plate type",
                lsTransaction: 1,
                lsType: "codeValue",
                lsTypeAndKind: "codeValue_plate type",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeTypeAndKind: "null_null",
                deleted: false,
                id: 497022,
                ignored: false,
                lsKind: "description",
                lsTransaction: 1,
                lsType: "stringValue",
                lsTypeAndKind: "stringValue_description",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                stringValue: "CMG00443:CQ 10UL",
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeKind: "kplate id",
                codeOrigin: "KPLATE",
                codeType: "kplate id",
                codeTypeAndKind: "kplate id_kplate id",
                codeValue: "311713",
                deleted: false,
                id: 497454,
                ignored: false,
                lsKind: "k plate id",
                lsTransaction: 1,
                lsType: "codeValue",
                lsTypeAndKind: "codeValue_k plate id",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeTypeAndKind: "null_null",
                deleted: false,
                id: 497023,
                ignored: false,
                lsKind: "created user",
                lsTransaction: 1,
                lsType: "stringValue",
                lsTypeAndKind: "stringValue_created user",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                stringValue: "cmg_user",
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeKind: "supplier code",
                codeOrigin: "KPLATE",
                codeType: "supplier code",
                codeTypeAndKind: "supplier code_supplier code",
                codeValue: "BOF002",
                deleted: false,
                id: 497639,
                ignored: false,
                lsKind: "supplier code",
                lsTransaction: 1,
                lsType: "codeValue",
                lsTypeAndKind: "codeValue_supplier code",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeKind: "availability",
                codeType: "availability",
                codeTypeAndKind: "availability_availability",
                codeValue: "0",
                deleted: false,
                id: 497358,
                ignored: false,
                lsKind: "availability",
                lsTransaction: 1,
                lsType: "codeValue",
                lsTypeAndKind: "codeValue_availability",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeTypeAndKind: "null_null",
                dateValue: 1370298139000,
                deleted: false,
                id: 497210,
                ignored: false,
                lsKind: "created date",
                lsTransaction: 1,
                lsType: "dateValue",
                lsTypeAndKind: "dateValue_created date",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }, {
                codeTypeAndKind: "null_null",
                dateValue: 1370298139000,
                deleted: false,
                id: 497211,
                ignored: false,
                lsKind: "registration date",
                lsTransaction: 1,
                lsType: "dateValue",
                lsTypeAndKind: "dateValue_registration date",
                operatorTypeAndKind: "null_null",
                publicData: true,
                recordedBy: "acas",
                recordedDate: 1455323304684,
                unitTypeAndKind: "null_null",
                version: 0
              }
            ],
            recordedBy: "acas",
            recordedDate: 1455323304684,
            version: 0
          }
        ],
        lsTransaction: 1,
        lsType: "container",
        lsTypeAndKind: "container_plate",
        recordedBy: "acas",
        recordedDate: 1455323304684,
        version: 0
      };
      return plates.push(plate);
    });
    return plates;
  };

  generateWells = function(plateType) {
    var j, maxCol, maxRow, results1, wellIndex, wells;
    maxCol = 12;
    maxRow = 8;
    if (plateType === "2-well") {
      maxCol = 1;
      maxRow = 2;
    } else if (plateType === "96-well") {
      maxCol = 12;
      maxRow = 8;
    } else if (plateType === "384-well") {
      maxCol = 24;
      maxRow = 16;
    } else if (plateType === "1536-well") {
      maxCol = 48;
      maxRow = 32;
    }
    wellIndex = 1;
    wells = [];
    _.each((function() {
      results1 = [];
      for (var j = 1; 1 <= maxCol ? j <= maxCol : j >= maxCol; 1 <= maxCol ? j++ : j--){ results1.push(j); }
      return results1;
    }).apply(this), function(colIdx) {
      var k, results2;
      return _.each((function() {
        results2 = [];
        for (var k = 1; 1 <= maxRow ? k <= maxRow : k >= maxRow; 1 <= maxRow ? k++ : k--){ results2.push(k); }
        return results2;
      }).apply(this), function(rowIdx) {
        var batchId, well;
        batchId = batchIds[Math.floor(Math.random() * _.size(batchIds)) + 1];
        well = {
          codeName: "WELL-" + wellIndex,
          columnIndex: colIdx,
          deleted: false,
          id: wellIndex,
          ignored: false,
          lsKind: "default",
          lsLabels: [
            {
              deleted: false,
              id: 206888,
              ignored: false,
              labelText: "N036",
              lsKind: "well name",
              lsTransaction: 1,
              lsType: "name",
              lsTypeAndKind: "name_well name",
              physicallyLabled: false,
              preferred: true,
              recordedBy: "acas",
              recordedDate: 1455323310690,
              version: 0
            }
          ],
          lsStates: [
            {
              deleted: false,
              id: 178897,
              ignored: false,
              lsKind: "content",
              lsTransaction: 1,
              lsType: "status",
              lsTypeAndKind: "status_content",
              lsValues: [
                {
                  codeKind: "solvent code",
                  codeType: "solvent code",
                  codeTypeAndKind: "solvent code_solvent code",
                  codeValue: "DNS000000001::1",
                  deleted: false,
                  id: 930194,
                  ignored: false,
                  lsKind: "solvent code",
                  lsTransaction: 1,
                  lsType: "codeValue",
                  lsTypeAndKind: "codeValue_solvent code",
                  operatorTypeAndKind: "null_null",
                  publicData: true,
                  recordedBy: "acas",
                  recordedDate: 1455323310690,
                  unitTypeAndKind: "null_null",
                  version: 0
                }, {
                  codeKind: "physical",
                  codeType: "state",
                  codeTypeAndKind: "state_physical",
                  codeValue: "liquid",
                  deleted: false,
                  id: 804246,
                  ignored: false,
                  lsKind: "physical state",
                  lsTransaction: 1,
                  lsType: "codeValue",
                  lsTypeAndKind: "codeValue_physical state",
                  operatorTypeAndKind: "null_null",
                  publicData: true,
                  recordedBy: "acas",
                  recordedDate: 1455323310690,
                  unitTypeAndKind: "null_null",
                  version: 0
                }, {
                  codeTypeAndKind: "null_null",
                  deleted: false,
                  id: 568849,
                  ignored: false,
                  lsKind: "amount",
                  lsTransaction: 1,
                  lsType: "numericValue",
                  lsTypeAndKind: "numericValue_amount",
                  numericValue: 10,
                  operatorTypeAndKind: "null_null",
                  publicData: true,
                  recordedBy: "acas",
                  recordedDate: 1455323310690,
                  unitKind: "uL",
                  unitTypeAndKind: "null_uL",
                  version: 0
                }, {
                  codeKind: "batch code",
                  codeType: "batch code",
                  codeTypeAndKind: "batch code_batch code",
                  codeValue: "DNS" + batchId + "::1",
                  concUnit: "mM",
                  concentration: 1,
                  deleted: false,
                  id: 636917,
                  ignored: false,
                  lsKind: "batch code",
                  lsTransaction: 1,
                  lsType: "codeValue",
                  lsTypeAndKind: "codeValue_batch code",
                  operatorTypeAndKind: "null_null",
                  publicData: true,
                  recordedBy: "acas",
                  recordedDate: 1455323310690,
                  unitTypeAndKind: "null_null",
                  version: 0
                }
              ],
              recordedBy: "acas",
              recordedDate: 1455323310690,
              version: 0
            }
          ],
          lsTransaction: 1,
          lsType: "well",
          lsTypeAndKind: "well_default",
          recordedBy: "acas",
          recordedDate: 1455323310690,
          rowIndex: rowIdx,
          version: 0
        };
        wellIndex++;
        return wells.push(well);
      });
    });
    return wells;
  };

  plate = generatePlates(500, "1536-well");

  console.time("dbBulkInsert");

  db.plates.insert(plate, function(err) {
    if (err) {
      console.log("err");
      return console.log(err);
    } else {
      db.plates.createIndex({
        "wells.lsStates.lsValues.codeValue": 1,
        "wells.lsStates.lsValues.lsKind": 1
      });
      db.plates.createIndex({
        "wells.lsStates.lsValues.lsKind": 1
      });
      console.log("loaded everything fine....");
      return console.timeEnd("dbBulkInsert");
    }
  });

  findWellsWithBatchCode = function(batchCode, callback) {};

}).call(this);
