### Compound data operations start here
getAssayCompoundData <- function (filePath, plateData, testMode, tempFilePath, assayData, userBypassInventory) {
  
  # If user selects case = No Inventory, userBypassInventory is TRUE
  #userBypassInventory <- TRUE 
  
  if (userBypassInventory) {
    # Table assayCompoundDT is generated by queries to the db to acquired the following: assayBarcode, cmpdBarcode, sourceType, plateType
    # Table assayCompoundDT is fed to the function immediately below, formatCompoundData()
    # Replace formatCompoundData() by providing allCompounData directly with all info from the plate template without inventory
    
    # Point to the proper file on my local machine (hard-coded filepath <-- TO BE RECTIFIED)
    testExcelFile <- "privateUploads/example_plateData_without_inventory_384_PCNC.xlsx" ## including PC, NC
    #testExcelFile <- "/Users/vasileios/Desktop/example_plateData_without_inventory_384.xlsx"
    
    # Extract info from all tabs of the file
    allCompoundData <- getPlateContent(testExcelFile)
    # Check if concentration units are uM
    microMolarFlag <- checkPlateConcentrationMicromolarUnits(allCompoundData)
    # Turn formatted dataframe to data table
    allCompoundData <- as.data.table(formatPlateContent(allCompoundData))
    
  } else {
    assayCompoundDT <- getPinTransfer(plateAssociationDT=plateData, testMode=testMode, tempFilePath=tempFilePath)
    
    allCompoundData <- formatCompoundData(assayCompoundDT, assayData, testMode=testMode, tempFilePath=tempFilePath)
  }
    
  # Check to make sure that wells don't have more than one compound listed
  overlappingPlate <- Filter(function(x) {length(unique(allCompoundData[assayBarcode == x, wellReference])) != 
                                                        length(allCompoundData[assayBarcode == x, wellReference])}, 
                             unique(allCompoundData[, assayBarcode]))
  if(length(overlappingPlate) > 0) {
    stopUser(paste0("Some sidecar and compound plates have overlapping wells.\n ",
                    "Please check the plates associated with the following assay barcode(s): ", 
                    paste(unlist(overlappingPlate), collapse=", ")))
  }
  
  setkeyv(allCompoundData, c("assayBarcode", "wellReference"))
  setkeyv(assayData, c("assayBarcode", "wellReference"))
  
  allAssayCompoundData <- merge(assayData, allCompoundData, all.x=TRUE)
  setkeyv(allAssayCompoundData, c("assayBarcode", "rowName", "wellReference"))
  
  allAssayCompoundData[ , assayFileName := NULL]
  
  colOrder <- c("plateType","assayBarcode","cmpdBarcode","sourceType","wellReference",
                "rowName","colName","corp_name","batch_number","cmpdConc","supplier","plateOrder")
  
  activityColumns <- setdiff(colnames(allAssayCompoundData), colOrder)
  setcolorder(allAssayCompoundData, c(colOrder, activityColumns))
  
  #setwd(normalizePath("../Analysis/"))
  write.table(allAssayCompoundData, file=file.path(tempFilePath, "output_well_data.srf"), append=FALSE, quote=FALSE, sep="\t", row.names=FALSE, col.names=TRUE, na="")
  
  # Needs to return a list for error catching
  # return(list(filePath=filePath, activity=allAssayCompoundData[ , activityColumns, with=FALSE]))
  
  if (userBypassInventory) {
    return(list(filePath=filePath, allAssayCompoundData=allAssayCompoundData, activityColNames=activityColumns, microMolarFlag=microMolarFlag))
  } else {
    return(list(filePath=filePath, allAssayCompoundData=allAssayCompoundData, activityColNames=activityColumns))
  }
  
}