### Compound data operations start here
getAssayCompoundData <- function (filePath, plateData, testMode, tempFilePath, assayData) {
  
  # Table assayCompoundDT is generated by queries to the db to acquired the following: assayBarcode, cmpdBarcode, sourceType, plateType
  # Table assayCompoundDT is fed to the function immediately below, formatCompoundData()
  #assayCompoundDT <- getPinTransfer(plateAssociationDT=plateData, testMode=testMode, tempFilePath=tempFilePath)
  
  # Replace formatCompoundData() by providing allCompounData directly with all info from the plate template without inventory
  #allCompoundData <- formatCompoundData(assayCompoundDT, assayData, testMode=testMode, tempFilePath=tempFilePath)
  
  # Point to the proper file on my local machine (hard-coded filepath <-- TO BE RECTIFIED)
  testExcelFile <- "/Users/vasileios/Desktop/example_plateData_without_inventory_384.xlsx"
  # Extract info from all tabs of the file
  allCompoundData <- getPlateContent(testExcelFile)
  # Check if concentration units are uM
  microMolarFlag <- checkPlateConcentrationMicromolarUnits(allCompoundData)
  # Turn formatted dataframe to data table
  allCompoundData <- as.data.table(formatPlateContent(allCompoundData))
  
  # Check to make sure that wells don't have more than one compound listed
  overlappingPlate <- Filter(function(x) {length(unique(allCompoundData[assayBarcode == x, wellReference])) != 
                                                        length(allCompoundData[assayBarcode == x, wellReference])}, 
                             unique(allCompoundData[, assayBarcode]))
  if(length(overlappingPlate) > 0) {
    stopUser(paste0("Some sidecar and compound plates have overlapping wells.\n ",
                    "Please check the plates associated with the following assay barcode(s): ", 
                    paste(unlist(overlappingPlate), collapse=", ")))
  }
  
  setkeyv(allCompoundData, c("assayBarcode", "wellReference"))
  setkeyv(assayData, c("assayBarcode", "wellReference"))
  
  allAssayCompoundData <- merge(assayData, allCompoundData, all.x=TRUE)
  setkeyv(allAssayCompoundData, c("assayBarcode", "rowName", "wellReference"))
  
  allAssayCompoundData[ , assayFileName := NULL]
  
  colOrder <- c("plateType","assayBarcode","cmpdBarcode","sourceType","wellReference",
                "rowName","colName","corp_name","batch_number","cmpdConc","supplier","plateOrder")
  
  activityColumns <- setdiff(colnames(allAssayCompoundData), colOrder)
  setcolorder(allAssayCompoundData, c(colOrder, activityColumns))
  
  #setwd(normalizePath("../Analysis/"))
  write.table(allAssayCompoundData, file=file.path(tempFilePath, "output_well_data.srf"), append=FALSE, quote=FALSE, sep="\t", row.names=FALSE, col.names=TRUE, na="")
  
  # Needs to return a list for error catching
  # return(list(filePath=filePath, activity=allAssayCompoundData[ , activityColumns, with=FALSE]))
  return(list(filePath=filePath, allAssayCompoundData=allAssayCompoundData, activityColNames=activityColumns, microMolarFlag=microMolarFlag))
}