GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA audit TO acas;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA audit TO compound_admin;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA audit TO acas;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA audit TO compound_admin;