<script type="text/template" id="EditParentSearch_template">

	<h2 class="form_title">Edit Parent Step 1: Draw Structure</h2>

	<div class="marvinWrapper"> <!--dependent? change name...-->
		<iframe id="editParentMarvinSketch" class="sketcher-frame"></iframe>
	</div>

	<div class="buttons">
		<a class="nextButton" href="#" onclick="this.blur(); return false;"><span></span></a>
		<a class="cancelEditButton" href="#" onclick="this.blur(); return false;"><span></span></a>
	</div>

    <div class="editParentSearchMarvinSize"></div>

</script>