<script type="text/template" id="StructureImage_template">

    <div class="structWrapper">
        <div class="structImageWrapper">
            <img class="structImage"/>
        </div>
        <div class="copyButtonWrapper">
            <img class="copyButton" src="/CmpdReg/client/images/glyphicon-copy.png"/>
        </div>
    </div>
    <div class="copyTextPanel" style="display:none">
        <textarea class="molCopyTextArea" rows="20" cols="90"></textarea>
        <div class="copyPanelCloseButtonWrapper">
            <a class="copyPanelCloseButton" href="#" onclick="this.blur(); return false;"></a>
        </div>
    </div>
</script>