getFormatSettings <- function() {
  formatSettings <- list(
    "DNS In Vivo Behavior" = list(
      annotationType = "s_behavior",
      hideAllData = TRUE,
      extraHeaders = data.frame(),
      stateGroups = list(list(entityKind = "subject",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Condition", "Dose", "Vehicle", "Administration route","Treatment Time"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              includesOthers = TRUE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              stateType = "metadata",
                              stateKind = "animal information",
                              valueKinds = c("Species","Strain","Sex","Vendor","Date of Arrival", "Date of Birth", "Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              labelType = "name",
                              labelKind = "container name",
                              labelText = "Animal ID",
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE))
    ), "In Vivo Full PK" = list(
      annotationType = "s_dmpk",
      hideAllData = FALSE,
      extraHeaders = data.frame(),
      sigFigs = 3,
      curveNames = c("PO IV pk curve id", "PO pk curve id", "IV pk curve id"),
      stateGroups = list(list(entityKind = "analysis group",
                              stateType = "data",
                              stateKind = "calculated data",
                              valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                             "PO - HL_Lambda_z", "PO - Tmax", 
                                             "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                             "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                             "IV - Vss_obs", "PO - Vss_obs"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "container",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("Gender", "Species"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              labelType = "name",
                              labelKind = "container name",
                              labelText = "Animal",
                              valueKinds = c("Animal"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Formulation", "IV - Route", "PO - Route", "Dose", "IV - food_effect", "PO - food_effect"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                             "PO - HL_Lambda_z", "IV - Tmax", "PO - Tmax", 
                                             "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                             "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                             "IV - Vss_obs", "PO - Vss_obs"),
                              includesOthers = TRUE,
                              includesCorpName = FALSE))
    ), "CNS PK" = list(
      annotationType = "s_dmpk",
      hideAllData = FALSE,
      sigFigs = 3,
      extraHeaders = data.frame(),
      stateGroups = list(list(entityKind = "analysis group",
                              stateType = "data",
                              stateKind = "calculated data",
                              valueKinds = c("PO Dose", "Time", "Plasma Conc.", "CSF Conc.", 
                                             "Brain Conc.", "B/P Ratio", "Formulation", "Species"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "container",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("Animal"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              labelType = "name",
                              labelKind = "container name",
                              labelText = "Animal",
                              valueKinds = c("Animal"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Formulation", "PO Dose", "Species"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              valueKinds = c("Time", "Plasma Conc.", "CSF Conc.", 
                                             "Brain Conc.", "B/P Ratio"),
                              includesOthers = TRUE,
                              includesCorpName = FALSE))
    ), "DNS Locomotor" = list(
      annotationType = "s_behavior",
      hideAllData = TRUE,
      extraHeaders = data.frame(),
      splitStates = c("Bin"),
      splitSubjects = c("Animal ID"),
      includeTreatmentGroupData = FALSE,
      rowMeaning = "subjectState",
      stateGroups = list(list(entityKind = "subject",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Dose", "Vehicle", "Administration route","Treatment Time"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              includesOthers = TRUE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              stateType = "metadata",
                              stateKind = "animal information",
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              labelType = "name",
                              labelKind = "container name",
                              labelText = "Animal ID",
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE))
    )
  )
  return(formatSettings)
} 