getFormatSettings <- function() {
  formatSettings <- list(
    "DNS In Vivo Behavior" = list(
      hideAllData = TRUE,
      extraHeaders = data.frame(),
      stateGroups = list(list(entityKind = "subject",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Condition", "Dose", "Vehicle", "Administration route","Treatment Time"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              includesOthers = TRUE,
                              includesCorpName = FALSE),
                         list(entityKind = "container",
                              stateType = "metadata",
                              stateKind = "animal information",
                              valueKinds = c("Species","Strain","Sex","Vendor","Date of Arrival", "Date of Birth", "Animal ID"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE))
    ), "In Vivo Full PK" = list(
      hideAllData = FALSE,
      extraHeaders = data.frame(headers = "In Life Notebook", class = "Text", isNullable = TRUE),
      stateGroups = list(list(entityKind = "analysis group",
                              stateType = "data",
                              stateKind = "calculated data",
                              valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                             "PO - HL_Lambda_z", "IV - Tmax", "PO - Tmax", 
                                             "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                             "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                             "IV - Vss_obs", "PO - Vss_obs"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "metadata", 
                              stateKind = "animal information", 
                              valueKinds = c("IV - Animal", "PO - Animal", "IV - Gender", "PO - Gender"),
                              includesOthers = FALSE,
                              includesCorpName = FALSE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "treatment",
                              valueKinds = c("Formulation", "IV - Route", "PO - Route", "IV - Dose", "PO - Dose", "IV - food_effect", "PO - food_effect"),
                              includesOthers = FALSE,
                              includesCorpName = TRUE),
                         list(entityKind = "subject",
                              stateType = "data",
                              stateKind = "raw data",
                              valueKinds = c("PO - Bioavailability", "IV - C0", "PO - Cmax", "IV - HL_Lambda_z", 
                                             "PO - HL_Lambda_z", "IV - Tmax", "PO - Tmax", 
                                             "IV - AUClast", "PO - AUClast", "IV - AUCINF_obs", "PO - AUCINF_obs",
                                             "IV - MRTlast", "PO - MRTlast", "IV - Cl_obs", "PO - Cl_obs",
                                             "IV - Vss_obs", "PO - Vss_obs"),
                              includesOthers = TRUE,
                              includesCorpName = FALSE))
    )
  )
  return(formatSettings)
} 