<script type="text/template" id="SearchResultsView_template">
	<h1 class="form_title">Search Results</h1>
	<div class="resultList">
    </div>
    <div class="buttons">
	<a class="exportButton" href="#" onclick="this.blur(); return false;"></a>
	<a class="closeButton" href="#" onclick="this.blur(); return false;"></a>
	<a class="backButton" href="#" onclick="this.blur(); return false;"></a>

    </div>

</script>