<script type="text/template" id="SearchResultView_template">

    <div class="searchResultHeader">
        <h2 class="corpName"></h2>
		<div class="mixture">
			<span class="stereoCategory"></span>
<!--			<span class="stereoComment"></span>-->
        	<select class="lotSelect"></select>
        	<span class="lotName"></span>

		</div>


    	<div class="searchResultButtons">
			<a class="detailsButton" href="#" onclick="this.blur(); return false;"></a>
			<a class="newLotButton" href="#" onclick="this.blur(); return false;"></a>
        </div>
    </div>
	<br />
	<div class="bv_aliasesContainer" ></div>
    <div class="resultImageWrapper">
    </div>


</script>
