<script type="text/template" id="SearchResultsView_template">
	<h1 class="form_title">Search Results</h1>
	<div class="resultList">
    </div>
    <div class="buttons">
	<a class="exportButton" href="#" onclick="this.blur(); return false;"></a>
	<a class="closeButton" href="#" onclick="this.blur(); return false;"></a>
	<a class="backButton" href="#" onclick="this.blur(); return false;"></a>

    </div>

    <div class="floatingPanel bv_downloadSearchResultsSdf hide">
       	<div class="bv_exportSearchResultsMessage"></div>
       	<div class="bv_downloadSearchResultsMessage">Click
        	<a class="bv_downloadSearchResultsLink">here</a>
        	to download the file.
		</div>
		<div class="closeExportSDF bv_closeExportSDF"></div>
    </div>

</script>