bulkFitErrorResponse =
  transactionId: -1
  results:
    htmlSummary: "\n\n<style type=\"text/css\">\n\n.racas_container {\n  max-width: 800px;\n  margin: auto;\n  line-height: 20px;\n}\n\n.racas_container tt, code, pre {\n   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;\n}\n\n.racas_container h1 { \n   font-size:2.2em; \n}\n\n.racas_container h2 { \n   font-size:1.8em; \n}\n\n.racas_container h3 { \n   font-size:1.4em; \n}\n\n.racas_container h4 { \n   font-size:1.0em; \n}\n\n.racas_container h5 { \n   font-size:0.9em; \n}\n\n.racas_container h6 { \n   font-size:0.8em; \n}\n\n/*.racas_container a:visited {\n   color: rgb(50%, 0%, 50%);\n}*/\n\n.racas_container pre, img {\n  max-width: 100%;\n}\n\n.racas_container pre code {\n   display: block; padding: 0.5em;\n}\n\n.racas_container code {\n  font-size: 92%;\n  border: 1px solid #ccc;\n}\n\n.racas_container code[class] {\n  background-color: #F8F8F8;\n}\n\n.racas_container table, td, th {\n  border: none;\n}\n\n.racas_container blockquote {\n   color:#666666;\n   margin:0;\n   padding-left: 1em;\n   border-left: 0.5em #EEE solid;\n}\n\n.racas_container hr {\n   height: 0px;\n   border-bottom: none;\n   border-top-width: thin;\n   border-top-style: dotted;\n   border-top-color: #999999;\n}\n\n@media print {\n   * { \n      background: transparent !important; \n      color: black !important; \n      filter:none !important; \n      -ms-filter: none !important; \n   }\n\n   body { \n      font-size:12pt; \n      max-width:100%; \n   }\n       \n   a, a:visited { \n      text-decoration: underline; \n   }\n\n   hr { \n      visibility: hidden;\n      page-break-before: always;\n   }\n\n   pre, blockquote { \n      padding-right: 1em; \n      page-break-inside: avoid; \n   }\n\n   tr, img { \n      page-break-inside: avoid; \n   }\n\n   img { \n      max-width: 100% !important; \n   }\n\n   @page :left { \n      margin: 15mm 20mm 15mm 10mm; \n   }\n     \n   @page :right { \n      margin: 15mm 10mm 15mm 20mm; \n   }\n\n   p, h2, h3 { \n      orphans: 3; widows: 3; \n   }\n\n   h2, h3 { \n      page-break-after: avoid; \n   }\n}\n\n</style>\n\n<div class=\"racas_container\">\n<h1>Fit Error Summary</h1>\n\n<p><strong><em>Errors</em></strong></p>\n\n<p>1: no experiment results found</p>\n\n</div>"
    status: "error"

  hasError: true
  hasWarning: false
  errorMessages: [ "no experiment results found" ]
